backend:
  name: github
  repo: markkaylor/silloh

media_folder: static/img
public_folder: /img

collections:
  - name: Product
    label: Product
    folder: src/pages/products
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image }
